
project_id = "jnupeddogxvcrqoolamn"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323
api_url = "http://localhost"

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
email_confirm_url = "http://localhost:3000/login"
email_confirm_redirect_url = "http://localhost:3000/login"

[analytics]
enabled = false

[functions]
[functions.create-notification]
verify_jwt = true

[functions.send-external-notification]
verify_jwt = true

[functions.get_daily_recommendations]
verify_jwt = true

[functions.get_user_chats]
verify_jwt = true

[functions.get_user_verification_status]
verify_jwt = true
