// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnupeddogxvcrqoolamn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudXBlZGRvZ3h2Y3Jxb29sYW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODU5NjAsImV4cCI6MjA2MTY2MTk2MH0.eyXP7LyEX7diQn5Kd4KZHIbDqJc-y4qaLw_G62oZldQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);