name: Auto Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 자동 커밋 - 파일 변경사항 반영"
          commit_author: GitHub Actions <actions@github.com>
          commit_options: '--no-verify'
          file_pattern: '**/*' 